# The app that holds the Limonada S.L. indexes and inputs

[install]
is_configured = true

[ui]
is_visible = true
label = Limonada SOC

[launcher]
author = Albeen
description = Indexes and inputs for the SOC in a Box lab
version = 0.1.0

[package]
id = limonada_soc
check_for_updates = false
