# The forwarder app for the Limonada S.L. Windows machines

[install]
is_configured = true

[ui]
is_visible = false
label = Limonada Forwarder

[launcher]
author = Albeen
description = Windows and Sysmon inputs, and where to send them
version = 0.1.0

[package]
id = limonada_forwarder
check_for_updates = false
